FROM node:22-bookworm-slim AS builder
RUN corepack enable && corepack prepare pnpm@latest --activate
COPY . /build
WORKDIR /build
RUN pnpm install --frozen-lockfile
RUN pnpm pack

FROM scratch
COPY --from=builder /build/openclaw-*.tgz /openclaw.tgz
